#!/usr/bin/env python3
"""
LucidUI build script.

Concatenates every .lua file in src/ (sorted by filename) into a single
dist/lucidui.lua file. The output is what users loadstring from GitHub.

Some modules are wrapped in `do ... end` blocks to avoid Luau's 200-local
register limit. Wrapping a module opens a fresh register frame, so its
top-level locals are freed once the block ends — even if captured as
upvalues by closures. This keeps the total count under the limit across
the entire concatenated chunk.

Usage:
    python build.py

Output:
    dist/lucidui.lua
"""

import os
import sys
import hashlib
from datetime import datetime, timezone
from pathlib import Path

# ------------------------------------------------------------------
# Config
# ------------------------------------------------------------------
ROOT     = Path(__file__).resolve().parent
SRC_DIR  = ROOT / "src"
DIST_DIR = ROOT / "dist"
OUTPUT   = DIST_DIR / "lucidui.lua"
VERSION  = "0.9.0"

# ------------------------------------------------------------------
# Modules that get wrapped in `do ... end`.
#
# Every top-level `local` in a Luau chunk consumes one of 200 register
# slots. Modules listed here have their locals freed the moment their
# wrapping block ends, so they don't count toward the limit.
#
# Only add a module here if:
#   1. It does NOT define locals consumed by other modules by name.
#   2. It DOES expose its API through LucidUI.* / Compat.* / globals.
#
# NEVER wrap these (they define shared locals used everywhere):
#   00_compat.lua, 01_helpers.lua, 01b_polish.lua,
#   02_themes.lua, 03_icons.lua
# ------------------------------------------------------------------
WRAP_MODULES = {
    "08f_webhook.lua",         # ~29 locals freed
    "08g_palette.lua",         # ~16 locals freed
    "08k_pergameconfigs.lua",  # ~14 locals freed
}

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def log(msg):
    print(f"[build] {msg}")

def fail(msg):
    print(f"[build] ERROR: {msg}", file=sys.stderr)
    sys.exit(1)

def short_hash(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:8]

# ------------------------------------------------------------------
# Collect sources
# ------------------------------------------------------------------
def collect_sources():
    if not SRC_DIR.exists():
        fail(f"src/ directory not found at {SRC_DIR}")

    files = sorted(SRC_DIR.glob("*.lua"))
    if not files:
        fail("no .lua files found in src/")

    log(f"found {len(files)} source file(s):")
    for f in files:
        size = f.stat().st_size
        wrapped = " [wrapped]" if f.name in WRAP_MODULES else ""
        log(f"  - {f.name} ({size} bytes){wrapped}")
    return files

# ------------------------------------------------------------------
# Header / footer
# ------------------------------------------------------------------
def make_header(file_list):
    names = ", ".join(f.name for f in file_list)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""--[[
    LucidUI v{VERSION}
    A modern, glass-morphism interface library for Roblox.

    Auto-generated by build.py on {now}
    Modules: {names}

    License: MIT
    Source: https://github.com/Kyootah/lucidui
]]

"""

def make_footer(content_hash):
    return f"""

--[[
    -- End of LucidUI v{VERSION} --
    Build: {content_hash}
]]
"""

# ------------------------------------------------------------------
# Read / wrap
# ------------------------------------------------------------------
def read_file(path):
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        log(f"warning: falling back to latin-1 for {path.name}")
        return path.read_text(encoding="latin-1")

def wrap_module(path, content):
    banner = (
        "-- ============================================================\n"
        f"-- Module: {path.name}\n"
        "-- ============================================================\n"
    )
    body = content.rstrip()

    if path.name in WRAP_MODULES:
        # Fresh register frame: locals inside are freed at `end`.
        # Indentation is intentionally omitted — Luau doesn't care, and
        # indenting thousands of lines of a wrapped module adds noise
        # without benefit. The banner comment still marks the module.
        return banner + "do\n" + body + "\nend\n\n"

    return banner + body + "\n\n"

# ------------------------------------------------------------------
# Build
# ------------------------------------------------------------------
def build():
    file_list = collect_sources()

    parts = [make_header(file_list)]
    for f in file_list:
        parts.append(wrap_module(f, read_file(f)))

    body = "".join(parts[1:])
    build_hash = short_hash(body.encode("utf-8"))
    parts.append(make_footer(build_hash))

    DIST_DIR.mkdir(exist_ok=True)
    OUTPUT.write_text("".join(parts), encoding="utf-8")

    size = OUTPUT.stat().st_size
    log(f"wrote {OUTPUT.relative_to(ROOT)} ({size} bytes, build {build_hash})")
    log("done.")

if __name__ == "__main__":
    build()
