#!/usr/bin/env python3
"""
LucidUI build script.

Concatenates every .lua file in src/ (sorted by filename) into a single
dist/lucidui.lua file.

Two invariants enforced by this build:

  1. No module may leave a top-level `return` in the concatenated
     output. Such a return would either be the last statement of the
     whole chunk (fine but redundant) or appear mid-chunk, which is a
     Lua syntax error: `Expected <eof>, got 'do'`. We strip them all.

  2. The final dist ends with a single `return LucidUI` so callers can
     use the standalone-load convenience:

         local LucidUI = loadstring(game:HttpGet(url))()

     That works because `LucidUI` is a *global* by the time 02_themes
     runs (`LucidUI = getgenv().LucidUI`), so it's in scope at EOF.

Usage:
    python build.py

Output:
    dist/lucidui.lua
"""

import os
import re           # ← PATCH: needed for strip_top_level_returns
import sys
import hashlib
from datetime import datetime, timezone
from pathlib import Path

# ------------------------------------------------------------------
# Config
# ------------------------------------------------------------------
ROOT     = Path(__file__).resolve().parent
SRC_DIR  = ROOT / "src"
DIST_DIR = ROOT / "dist"
OUTPUT   = DIST_DIR / "lucidui.lua"
VERSION  = "0.10.0"          # ← PATCH: matches 02_themes.lua's _version

# ------------------------------------------------------------------
# Modules that get wrapped in `do ... end`.
#
# Every top-level `local` in a Luau chunk consumes one of 200 register
# slots. Modules listed here have their locals freed the moment their
# wrapping block ends, so they don't count toward the limit.
#
# Only add a module here if:
#   1. It does NOT define locals consumed by other modules by name.
#   2. It DOES expose its API through LucidUI.* / Compat.* / globals.
#
# NEVER wrap these (they define shared locals used everywhere):
#   00_compat.lua, 01_helpers.lua, 01b_polish.lua,
#   02_themes.lua, 03_icons.lua
# ------------------------------------------------------------------
WRAP_MODULES = {
    "08f_webhook.lua",         # ~29 locals freed
    "08g_palette.lua",         # ~16 locals freed
    "08k_pergameconfigs.lua",  # ~14 locals freed
}

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def log(msg):
    print(f"[build] {msg}")

def fail(msg):
    print(f"[build] ERROR: {msg}", file=sys.stderr)
    sys.exit(1)

def short_hash(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:8]

# ------------------------------------------------------------------
# ← PATCH: strip top-level returns before concatenation
# ------------------------------------------------------------------
_TOP_LEVEL_RETURN = re.compile(r'^return\b[^\n]*$', re.MULTILINE)

def strip_top_level_returns(source: str):
    """
    Remove any top-level `return ...` statement (a line starting with
    `return` at column 0). Indented returns — inside functions, if
    blocks, loops — are left alone, since they're valid wherever they
    appear.

    Returns (cleaned_source, count_stripped).
    """
    count = len(_TOP_LEVEL_RETURN.findall(source))
    if count:
        source = _TOP_LEVEL_RETURN.sub('', source)
    return source, count

# ------------------------------------------------------------------
# Collect sources
# ------------------------------------------------------------------
def collect_sources():
    if not SRC_DIR.exists():
        fail(f"src/ directory not found at {SRC_DIR}")

    files = sorted(SRC_DIR.glob("*.lua"))
    if not files:
        fail("no .lua files found in src/")

    log(f"found {len(files)} source file(s):")
    for f in files:
        size = f.stat().st_size
        wrapped = " [wrapped]" if f.name in WRAP_MODULES else ""
        log(f"  - {f.name} ({size} bytes){wrapped}")
    return files

# ------------------------------------------------------------------
# Header / footer
# ------------------------------------------------------------------
def make_header(file_list):
    names = ", ".join(f.name for f in file_list)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""--[[
    LucidUI v{VERSION}
    A modern, glass-morphism interface library for Roblox.

    Auto-generated by build.py on {now}
    Modules: {names}

    License: MIT
    Source: https://github.com/Kyootah/lucidui
]]

"""

def make_footer(content_hash):
    # ← PATCH: single top-level return at EOF, so loadstring(...)()
    #   still hands back the LucidUI table to callers that want it.
    #   `LucidUI` is a global set in 01b_polish / 02_themes, so it's
    #   in scope here.
    return f"""

--[[
    -- End of LucidUI v{VERSION} --
    Build: {content_hash}
]]

return LucidUI
"""

# ------------------------------------------------------------------
# Read / wrap
# ------------------------------------------------------------------
def read_file(path):
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        log(f"warning: falling back to latin-1 for {path.name}")
        return path.read_text(encoding="latin-1")

def wrap_module(path, content):
    banner = (
        "-- ============================================================\n"
        f"-- Module: {path.name}\n"
        "-- ============================================================\n"
    )
    body = content.rstrip()

    # ← PATCH: strip top-level returns BEFORE wrapping/concatenating.
    body, stripped = strip_top_level_returns(body)
    if stripped:
        log(f"  stripped {stripped} top-level return(s) from {path.name}")

    if path.name in WRAP_MODULES:
        # Fresh register frame: locals inside are freed at `end`.
        return banner + "do\n" + body + "\nend\n\n"

    return banner + body + "\n\n"

# ------------------------------------------------------------------
# Build
# ------------------------------------------------------------------
def build():
    file_list = collect_sources()

    parts = [make_header(file_list)]
    for f in file_list:
        parts.append(wrap_module(f, read_file(f)))

    body = "".join(parts[1:])
    build_hash = short_hash(body.encode("utf-8"))
    parts.append(make_footer(build_hash))

    DIST_DIR.mkdir(exist_ok=True)
    OUTPUT.write_text("".join(parts), encoding="utf-8")

    size = OUTPUT.stat().st_size
    log(f"wrote {OUTPUT.relative_to(ROOT)} ({size} bytes, build {build_hash})")
    log("done.")

if __name__ == "__main__":
    build()
