#!/usr/bin/env python3
"""
LucidUI build script.

Concatenates every .lua file in src/ (sorted by filename) into a single
dist/lucidui.lua file. The output is what users loadstring from GitHub.

Usage:
    python build.py

Output:
    dist/lucidui.lua
"""

import os
import sys
import hashlib
from datetime import datetime, timezone
from pathlib import Path

# ------------------------------------------------------------------
# Config
# ------------------------------------------------------------------
ROOT     = Path(__file__).resolve().parent
SRC_DIR  = ROOT / "src"
DIST_DIR = ROOT / "dist"
OUTPUT   = DIST_DIR / "lucidui.lua"
VERSION  = "0.9.0"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def log(msg):
    print(f"[build] {msg}")

def fail(msg):
    print(f"[build] ERROR: {msg}", file=sys.stderr)
    sys.exit(1)

def short_hash(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:8]

# ------------------------------------------------------------------
# Collect sources
# ------------------------------------------------------------------
def collect_sources():
    if not SRC_DIR.exists():
        fail(f"src/ directory not found at {SRC_DIR}")

    files = sorted(SRC_DIR.glob("*.lua"))
    if not files:
        fail("no .lua files found in src/")

    log(f"found {len(files)} source file(s):")
    for f in files:
        size = f.stat().st_size
        log(f"  - {f.name} ({size} bytes)")
    return files

# ------------------------------------------------------------------
# Header / footer
# ------------------------------------------------------------------
def make_header(file_list):
    names = ", ".join(f.name for f in file_list)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return f"""--[[
    LucidUI v{VERSION}
    A modern, glass-morphism interface library for Roblox.

    Auto-generated by build.py on {now}
    Modules: {names}

    License: MIT
    Source: https://github.com/Kyootah/lucidui
]]

"""

def make_footer(content_hash):
    return f"""

--[[
    -- End of LucidUI v{VERSION} --
    Build: {content_hash}
]]
"""

# ------------------------------------------------------------------
# Read / wrap
# ------------------------------------------------------------------
def read_file(path):
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        log(f"warning: falling back to latin-1 for {path.name}")
        return path.read_text(encoding="latin-1")

def wrap_module(path, content):
    banner = (
        "-- ============================================================\n"
        f"-- Module: {path.name}\n"
        "-- ============================================================\n"
    )
    return banner + content.rstrip() + "\n\n"

# ------------------------------------------------------------------
# Build
# ------------------------------------------------------------------
def build():
    file_list = collect_sources()

    parts = [make_header(file_list)]
    for f in file_list:
        parts.append(wrap_module(f, read_file(f)))

    body = "".join(parts[1:])
    build_hash = short_hash(body.encode("utf-8"))
    parts.append(make_footer(build_hash))

    DIST_DIR.mkdir(exist_ok=True)
    OUTPUT.write_text("".join(parts), encoding="utf-8")

    size = OUTPUT.stat().st_size
    log(f"wrote {OUTPUT.relative_to(ROOT)} ({size} bytes, build {build_hash})")
    log("done.")

if __name__ == "__main__":
    build()
